// ============================================================
// GET /api/briefing
// Reply: { ok: true, reply: string, newsSource: 'web_search'|'rss_llm'|'rss_raw'|'unavailable',
//          generatedAt: number, cached: boolean } | { ok: false, error }
//
// v2 — pre-generated and cached. A Vercel Cron job (see vercel.json)
// hits this SAME endpoint once a day to warm the cache; a normal
// caller (Authorization: Bearer <ASSISTANT_API_TOKEN>) gets the cached
// reply back instantly if today's is already there, and only falls
// back to a live (slower) generation if it's missing — e.g. the cron
// hasn't fired yet today, or its run failed.
//
// NOTE ON WHY THIS IS ONE FILE, NOT TWO: Vercel's Hobby plan caps a
// deployment at 12 serverless functions when every file under api/ is
// its own route (no framework bundling) — and this project already
// has exactly 12. A separate api/generate-briefing.js would push past
// that limit and could break deployment. Instead, the cron job's
// request is just another GET to /api/briefing, authenticated with
// CRON_SECRET (Vercel's own convention — see SETUP.md §7) instead of
// ASSISTANT_API_TOKEN. Cron and normal requests run the exact same
// cache-or-generate logic; there is no behavioral branch on who's
// asking, only on which credential matched.
//
// Location is hardcoded to Evanston, IL (LAT/LON/TIMEZONE below) —
// there is no per-user location setting yet.
//
// STRUCTURE (exact, per explicit request — see FIXED_OPENING /
// FIXED_TRANSITION below): a fixed greeting, then a weather section
// computed ENTIRELY server-side from Open-Meteo data (condition, high/
// low, UV index, sunscreen window, umbrella yes/no — no hydration or
// other health tips), then a fixed transition line, then a Claude-
// generated news section. The greeting and transition are literal
// strings concatenated in code, NOT generated by the model — asking
// an LLM to reproduce an exact sentence verbatim on every call is far
// less reliable than just not asking it to. Likewise the weather
// section is plain arithmetic on real data, not model output, so
// there's nothing for it to hallucinate or omit.
//
// NEWS RELIABILITY: composeNewsSection() below NEVER throws and NEVER
// returns empty text — it tries Claude's web_search tool, then (on
// ANY failure, including a request-level 400 for web search being
// disabled, OR a same-200-response per-search error like
// max_uses_exceeded/too_many_requests — see evaluateSearchOutcome)
// falls back to Google News' free RSS feed summarized by Claude, then
// (if even that fails) the raw RSS headlines with no LLM involved at
// all, and only as an absolute last resort an honest one-line apology
// — never a blank section, never a fabricated headline.
//
// Auth: Authorization: Bearer <ASSISTANT_API_TOKEN> (normal callers)
//    or Authorization: Bearer <CRON_SECRET> (Vercel Cron — automatic,
//    see SETUP.md §7).
//
// Env vars required on Vercel:
//   ANTHROPIC_API_KEY
//   ASSISTANT_API_TOKEN
//   CRON_SECRET
//   SUPABASE_URL
//   SUPABASE_ANON_KEY
// ============================================================
import Anthropic from '@anthropic-ai/sdk';

// Evanston, Illinois — geocoded via Open-Meteo's free geocoding API
// (geocoding-api.open-meteo.com/v1/search?name=Evanston), not guessed.
const LAT = 42.04114;
const LON = -87.69006;
const TIMEZONE = 'America/Chicago';

// WHO/EPA UV Index scale: 0-2 Low (no protection needed), 3-5
// Moderate (protection recommended) — 3 is the standard "wear
// sunscreen" threshold, not an arbitrary guess.
const SUNSCREEN_UV_THRESHOLD = 3;
// Practical, documented cutoff — not an official standard, just a
// reasonable single number for a "simple yes or no" per the spec.
const UMBRELLA_PRECIP_PROB_THRESHOLD = 40;

const FIXED_OPENING = 'Good morning Deni, I see that you have slept well.';
const FIXED_TRANSITION = "Now it's time to direct your attention to what matters most.";

const SIMPLE_CONDITIONS = {
  0: 'clear and sunny', 1: 'mostly clear', 2: 'partly cloudy', 3: 'cloudy',
  45: 'foggy', 48: 'foggy',
  51: 'light rain', 53: 'rain', 55: 'rain',
  56: 'freezing rain', 57: 'freezing rain',
  61: 'light rain', 63: 'rain', 65: 'heavy rain',
  66: 'freezing rain', 67: 'freezing rain',
  71: 'light snow', 73: 'snow', 75: 'heavy snow',
  77: 'snow',
  80: 'rain showers', 81: 'rain showers', 82: 'heavy rain showers',
  85: 'snow showers', 86: 'heavy snow showers',
  95: 'thunderstorms', 96: 'thunderstorms', 99: 'thunderstorms',
};

function checkAuth(req) {
  const cronSecret = process.env.CRON_SECRET;
  const assistantToken = process.env.ASSISTANT_API_TOKEN;
  const header = (req.headers && req.headers.authorization) || '';
  const token = header.indexOf('Bearer ') === 0 ? header.slice(7) : '';
  if (cronSecret && token === cronSecret) return true;
  if (assistantToken && token === assistantToken) return true;
  return false;
}

async function readAppState(supabaseUrl, supabaseKey, key) {
  try {
    const r = await fetch(supabaseUrl + '/rest/v1/app_state?key=eq.' + key + '&select=data', {
      headers: { apikey: supabaseKey, Authorization: 'Bearer ' + supabaseKey },
    });
    if (!r.ok) return null;
    const rows = await r.json();
    return (rows && rows[0] && rows[0].data) || null;
  } catch (e) { return null; }
}

async function upsertAppState(supabaseUrl, supabaseKey, key, data) {
  return fetch(supabaseUrl + '/rest/v1/app_state?on_conflict=key', {
    method: 'POST',
    headers: {
      apikey: supabaseKey,
      Authorization: 'Bearer ' + supabaseKey,
      'Content-Type': 'application/json',
      Prefer: 'resolution=merge-duplicates',
    },
    body: JSON.stringify({ key, data, updated_at: new Date().toISOString() }),
  });
}

// en-CA formats as YYYY-MM-DD directly — used as the cache's
// freshness key so "today" is always evaluated in Evanston's actual
// local calendar day, independent of when/how imprecisely the cron
// itself fired.
export function getTodayDateKey(now) {
  now = now == null ? Date.now() : now;
  return new Intl.DateTimeFormat('en-CA', { timeZone: TIMEZONE, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(now));
}

function formatHourLabel(isoLocal) {
  const hourStr = isoLocal.split('T')[1] || '';
  const hour = parseInt(hourStr.split(':')[0], 10);
  if (!Number.isFinite(hour)) return '';
  const period = hour >= 12 ? 'PM' : 'AM';
  let h12 = hour % 12;
  if (h12 === 0) h12 = 12;
  return h12 + ' ' + period;
}

// Finds the first/last hour today where UV reaches SUNSCREEN_UV_THRESHOLD
// — null if it never does (e.g. an overcast winter day).
export function computeSunscreenWindow(hourlyTimes, hourlyUV, threshold) {
  threshold = threshold == null ? SUNSCREEN_UV_THRESHOLD : threshold;
  let startIdx = -1, endIdx = -1;
  for (let i = 0; i < hourlyUV.length; i++) {
    if (hourlyUV[i] != null && hourlyUV[i] >= threshold) {
      if (startIdx === -1) startIdx = i;
      endIdx = i;
    }
  }
  if (startIdx === -1) return null;
  return { startLabel: formatHourLabel(hourlyTimes[startIdx]), endLabel: formatHourLabel(hourlyTimes[endIdx]) };
}

export function computeUmbrellaAdvice(precipProbMaxPct, threshold) {
  threshold = threshold == null ? UMBRELLA_PRECIP_PROB_THRESHOLD : threshold;
  return precipProbMaxPct != null && precipProbMaxPct >= threshold;
}

// Pure — takes Open-Meteo's parsed JSON response and derives every
// field the weather section needs. Separated from fetchWeather() so
// it's testable with synthetic data, no network call required.
export function deriveWeatherFields(data) {
  const current = (data && data.current) || {};
  const daily = (data && data.daily) || {};
  const hourly = (data && data.hourly) || {};
  const weatherCode = current.weather_code;
  const highF = Array.isArray(daily.temperature_2m_max) ? daily.temperature_2m_max[0] : null;
  const lowF = Array.isArray(daily.temperature_2m_min) ? daily.temperature_2m_min[0] : null;
  const uvIndexMaxToday = Array.isArray(daily.uv_index_max) ? daily.uv_index_max[0] : null;
  const precipProbMaxPct = Array.isArray(daily.precipitation_probability_max) ? daily.precipitation_probability_max[0] : null;
  const hourlyTimes = Array.isArray(hourly.time) ? hourly.time : [];
  const hourlyUV = Array.isArray(hourly.uv_index) ? hourly.uv_index : [];
  return {
    condition: SIMPLE_CONDITIONS[weatherCode] || (weatherCode != null ? 'mixed conditions' : 'unknown conditions'),
    highF, lowF, uvIndexMaxToday, precipProbMaxPct,
    sunscreenWindow: computeSunscreenWindow(hourlyTimes, hourlyUV),
    needUmbrella: computeUmbrellaAdvice(precipProbMaxPct),
  };
}

export async function fetchWeather() {
  const url = 'https://api.open-meteo.com/v1/forecast' +
    '?latitude=' + LAT + '&longitude=' + LON +
    '&timezone=' + encodeURIComponent(TIMEZONE) +
    '&forecast_days=1' +
    '&current=weather_code' +
    '&hourly=uv_index' +
    '&daily=uv_index_max,precipitation_probability_max,temperature_2m_max,temperature_2m_min' +
    '&temperature_unit=fahrenheit&precipitation_unit=inch';
  const r = await fetch(url);
  if (!r.ok) throw new Error('Open-Meteo request failed: ' + r.status);
  const data = await r.json();
  return deriveWeatherFields(data);
}

// Deterministic, no LLM — condition/high-low/UV/sunscreen window/
// umbrella only. Deliberately excludes hydration and any other health
// tip per the explicit spec.
export function buildWeatherSection(w) {
  const parts = [];
  if (w.highF != null && w.lowF != null) {
    parts.push('Today\'s weather is ' + w.condition + ', with a high of ' + Math.round(w.highF) + ' and a low of ' + Math.round(w.lowF) + ' degrees.');
  } else {
    parts.push('Today\'s weather is ' + w.condition + '.');
  }
  if (w.uvIndexMaxToday != null) parts.push('The UV index is ' + w.uvIndexMaxToday + '.');
  if (w.sunscreenWindow) parts.push('Wear sunscreen between ' + w.sunscreenWindow.startLabel + ' and ' + w.sunscreenWindow.endLabel + '.');
  else parts.push('You won\'t need sunscreen today.');
  parts.push(w.needUmbrella ? 'Yes, bring an umbrella today.' : 'No, you won\'t need an umbrella today.');
  return parts.join(' ');
}

// ---------- News (Claude web_search, with a guaranteed-non-empty fallback chain) ----------

// A web_search_tool_result block's `content` is an ARRAY of results on
// success (possibly empty — "no matches" is not an error) or a single
// error OBJECT ({type:'web_search_tool_result_error', error_code}) on
// failure — e.g. max_uses_exceeded or too_many_requests. Both come
// back as a normal 200 response with the error embedded in this
// block, NOT a thrown exception, so a naive try/catch around the
// whole request misses it. This inspects the actual outcome so the
// caller can fall back whenever real search didn't produce anything
// usable, not just when the request failed outright.
export function evaluateSearchOutcome(content) {
  const resultBlocks = (content || []).filter((b) => b && b.type === 'web_search_tool_result');
  if (resultBlocks.length === 0) {
    return { ok: false, reason: 'no web search was performed for this request' };
  }
  const succeeded = resultBlocks.filter((b) => Array.isArray(b.content));
  if (succeeded.length === 0) {
    const codes = resultBlocks.map((b) => b.content && b.content.error_code).filter(Boolean);
    return { ok: false, reason: 'every web search attempt failed (' + (codes.length ? codes.join(', ') : 'unknown error') + ') — likely a rate limit or usage cap' };
  }
  return { ok: true, reason: null };
}

export function parseRSSTitles(xml, limit) {
  const items = [];
  const itemRegex = /<item>([\s\S]*?)<\/item>/g;
  let m;
  while ((m = itemRegex.exec(xml)) && items.length < limit) {
    const titleMatch = /<title>([\s\S]*?)<\/title>/.exec(m[1]);
    if (!titleMatch) continue;
    const title = titleMatch[1].replace(/<!\[CDATA\[/g, '').replace(/\]\]>/g, '').trim();
    if (title) items.push(title);
  }
  return items;
}

async function fetchNewsHeadlines(query) {
  const url = query
    ? 'https://news.google.com/rss/search?q=' + encodeURIComponent(query) + '&hl=en-US&gl=US&ceid=US:en'
    : 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en';
  const r = await fetch(url);
  if (!r.ok) throw new Error('news RSS request failed: ' + r.status);
  const xml = await r.text();
  return parseRSSTitles(xml, 12);
}

export function buildNewsPrompt(lifeContext, newsHeadlines) {
  const lines = [
    'Write ONLY the news portion of a spoken-word morning briefing — plain conversational text, no markdown, no headers, no bullet points, no numbered lists, no asterisks, and no preamble like "Here are the top stories."',
    'Pick the 3 news stories most relevant to these interests, each as one or two spoken sentences:',
    lifeContext ? lifeContext : '(not set — pick broadly interesting, non-partisan headlines instead)',
  ];
  if (newsHeadlines && newsHeadlines.length) {
    lines.push(
      '',
      'Live web search was not available for this request. Choose the 3 most relevant headlines from this fixed list instead of searching — do not invent stories not on this list:',
      newsHeadlines.map((h) => '- ' + h).join('\n'),
    );
  } else {
    lines.push('', 'Use web search to find today\'s real, current top stories relevant to those interests.');
  }
  return lines.join('\n');
}

async function newsViaWebSearch(client, lifeContext) {
  const messages = [{ role: 'user', content: buildNewsPrompt(lifeContext, null) }];
  for (let i = 0; i < 4; i++) {
    const response = await client.messages.create({
      model: 'claude-opus-4-8',
      max_tokens: 1024,
      tools: [{ type: 'web_search_20260209', name: 'web_search', max_uses: 5 }],
      messages,
    });
    if (response.stop_reason === 'pause_turn') {
      messages.push({ role: 'assistant', content: response.content });
      continue;
    }
    const outcome = evaluateSearchOutcome(response.content);
    if (!outcome.ok) throw new Error(outcome.reason);
    return response.content.filter((b) => b.type === 'text').map((b) => b.text).join(' ').trim();
  }
  throw new Error('web search turn did not complete after multiple pauses');
}

async function newsViaRSSAndLLM(client, lifeContext) {
  const query = lifeContext ? lifeContext.slice(0, 200) : '';
  const headlines = await fetchNewsHeadlines(query);
  if (!headlines.length) throw new Error('RSS feed returned no headlines');
  const response = await client.messages.create({
    model: 'claude-opus-4-8',
    max_tokens: 1024,
    messages: [{ role: 'user', content: buildNewsPrompt(lifeContext, headlines) }],
  });
  return response.content.filter((b) => b.type === 'text').map((b) => b.text).join(' ').trim();
}

export function newsViaRawHeadlines(headlines) {
  return 'In the news: ' + headlines.slice(0, 3).join('. ') + '.';
}

// Four-tier fallback: web search -> RSS summarized by Claude -> raw
// RSS headlines (no LLM at all) -> an honest one-line apology. Never
// throws, never returns an empty string — this section is guaranteed
// non-empty by construction, not by hope.
export async function composeNewsSection(client, lifeContext) {
  try {
    const text = await newsViaWebSearch(client, lifeContext);
    if (text) return { text, source: 'web_search' };
    throw new Error('web search path returned no text');
  } catch (e1) {
    try {
      const text = await newsViaRSSAndLLM(client, lifeContext);
      if (text) return { text, source: 'rss_llm' };
      throw new Error('rss+LLM path returned no text');
    } catch (e2) {
      try {
        const query = lifeContext ? lifeContext.slice(0, 200) : '';
        const headlines = await fetchNewsHeadlines(query);
        if (!headlines.length) throw new Error('no headlines');
        return { text: newsViaRawHeadlines(headlines), source: 'rss_raw' };
      } catch (e3) {
        return { text: 'I wasn\'t able to pull today\'s news due to a technical issue — everything else in this briefing is accurate.', source: 'unavailable' };
      }
    }
  }
}

// ---------- Cache ----------

async function readCachedBriefing(supabaseUrl, supabaseKey) {
  const state = await readAppState(supabaseUrl, supabaseKey, 'briefing_cache');
  const cached = state && state.briefing_v1;
  if (!cached || typeof cached.reply !== 'string' || !cached.reply) return null;
  if (cached.dateKey !== getTodayDateKey()) return null;
  return cached;
}

export async function generateBriefing(apiKey, supabaseUrl, supabaseKey) {
  const weather = await fetchWeather();
  const weatherSection = buildWeatherSection(weather);

  const lifeContextState = await readAppState(supabaseUrl, supabaseKey, 'life_context');
  const lifeContext = (lifeContextState && typeof lifeContextState.life_context_v1 === 'string') ? lifeContextState.life_context_v1 : '';

  const client = new Anthropic({ apiKey });
  const { text: newsSection, source: newsSource } = await composeNewsSection(client, lifeContext);

  const reply = [FIXED_OPENING, weatherSection, FIXED_TRANSITION, newsSection].join(' ').replace(/\s+/g, ' ').trim();
  const generatedAt = Date.now();
  const dateKey = getTodayDateKey(generatedAt);

  await upsertAppState(supabaseUrl, supabaseKey, 'briefing_cache', { briefing_v1: { reply, newsSource, generatedAt, dateKey } });

  return { reply, newsSource, generatedAt };
}

export default async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).json({ ok: false, error: 'method not allowed' });
  if (!checkAuth(req)) return res.status(401).json({ ok: false, error: 'invalid or missing bearer token' });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return res.status(500).json({ ok: false, error: 'ANTHROPIC_API_KEY not configured' });
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;
  if (!supabaseUrl || !supabaseKey) return res.status(500).json({ ok: false, error: 'server not configured (missing SUPABASE_URL / SUPABASE_ANON_KEY)' });

  const cached = await readCachedBriefing(supabaseUrl, supabaseKey);
  if (cached) {
    return res.status(200).json({ ok: true, reply: cached.reply, newsSource: cached.newsSource, generatedAt: cached.generatedAt, cached: true });
  }

  try {
    const { reply, newsSource, generatedAt } = await generateBriefing(apiKey, supabaseUrl, supabaseKey);
    return res.status(200).json({ ok: true, reply, newsSource, generatedAt, cached: false });
  } catch (e) {
    return res.status(200).json({ ok: false, error: 'briefing generation failed: ' + (e && e.message ? e.message : String(e)) });
  }
}
