// ============================================================
// GET /api/briefing
// Reply: { ok: true, reply: string, newsSource: 'rss_llm'|'rss_raw'|'unavailable',
//          generatedAt: number, cached: boolean } | { ok: false, error }
//
// v3 — RSS is the PRIMARY (only) news source; Claude's web_search tool
// is not used at all in this endpoint. v2 tried web_search first with
// RSS as a fallback, but the fallback prompt told Claude "live web
// search was not available for this request" — and Claude, given that
// framing, sometimes wrote a long apologetic explanation of the search
// failure instead of just using the provided headlines, which is what
// actually surfaced as "a long rambling apology" in production. RSS
// being primary (not a fallback being explained away) removes that
// framing entirely, and also means this endpoint can never hit a web
// search rate/usage limit or add web search's per-search cost.
//
// News gathering, in code (not model-driven): fetchCategorizedHeadlines()
// below keyword-matches the Life Context text against a small fixed
// set of topics (AI/tech, biomedical, markets) and fetches each
// matched topic's Google News RSS search feed (free, keyless) in
// parallel, always alongside the general top-stories feed as a
// baseline. Claude then only SELECTS and SUMMARIZES from that fixed,
// real headline list — it is never asked to search, and the prompt
// never mentions search/RSS/technical details at all, so there is
// nothing for it to comment on or apologize about.
//
// v2 — pre-generated and cached. A Vercel Cron job (see vercel.json)
// hits this SAME endpoint once a day to warm the cache; a normal
// caller (Authorization: Bearer <ASSISTANT_API_TOKEN>) gets the cached
// reply back instantly if today's is already there, and only falls
// back to a live (slower) generation if it's missing — e.g. the cron
// hasn't fired yet today, or its run failed.
//
// NOTE ON WHY THIS IS ONE FILE, NOT TWO: Vercel's Hobby plan caps a
// deployment at 12 serverless functions when every file under api/ is
// its own route (no framework bundling) — and this project already
// has exactly 12. A separate api/generate-briefing.js would push past
// that limit and could break deployment. Instead, the cron job's
// request is just another GET to /api/briefing, authenticated with
// CRON_SECRET (Vercel's own convention — see SETUP.md §7) instead of
// ASSISTANT_API_TOKEN. Cron and normal requests run the exact same
// cache-or-generate logic; there is no behavioral branch on who's
// asking, only on which credential matched.
//
// Location is hardcoded to Evanston, IL (LAT/LON/TIMEZONE below) —
// there is no per-user location setting yet.
//
// STRUCTURE (exact, per explicit request — see FIXED_OPENING /
// FIXED_TRANSITION below): a fixed greeting, then a weather section
// computed ENTIRELY server-side from Open-Meteo data (condition, high/
// low, UV index, sunscreen window, umbrella yes/no — no hydration or
// other health tips), then a fixed transition line, then a Claude-
// generated news section. The greeting and transition are literal
// strings concatenated in code, NOT generated by the model — asking
// an LLM to reproduce an exact sentence verbatim on every call is far
// less reliable than just not asking it to. Likewise the weather
// section is plain arithmetic on real data, not model output, so
// there's nothing for it to hallucinate or omit.
//
// NEWS RELIABILITY: composeNewsSection() below NEVER throws and NEVER
// returns empty text — Claude summarizes the fetched RSS headlines
// (source 'rss_llm'); if the LLM call itself fails, the raw headlines
// are used directly with no LLM involved (source 'rss_raw'); only if
// every RSS feed is also unreachable does it fall to a single short,
// honest sentence (source 'unavailable') — never a blank section,
// never a fabricated headline, and never more than one sentence.
//
// Auth: Authorization: Bearer <ASSISTANT_API_TOKEN> (normal callers)
//    or Authorization: Bearer <CRON_SECRET> (Vercel Cron — automatic,
//    see SETUP.md §7).
//
// Env vars required on Vercel:
//   ANTHROPIC_API_KEY
//   ASSISTANT_API_TOKEN
//   CRON_SECRET
//   SUPABASE_URL
//   SUPABASE_ANON_KEY
// ============================================================
import Anthropic from '@anthropic-ai/sdk';

// Evanston, Illinois — geocoded via Open-Meteo's free geocoding API
// (geocoding-api.open-meteo.com/v1/search?name=Evanston), not guessed.
const LAT = 42.04114;
const LON = -87.69006;
const TIMEZONE = 'America/Chicago';

// WHO/EPA UV Index scale: 0-2 Low (no protection needed), 3-5
// Moderate (protection recommended) — 3 is the standard "wear
// sunscreen" threshold, not an arbitrary guess.
const SUNSCREEN_UV_THRESHOLD = 3;
// Practical, documented cutoff — not an official standard, just a
// reasonable single number for a "simple yes or no" per the spec.
const UMBRELLA_PRECIP_PROB_THRESHOLD = 40;

const FIXED_OPENING = 'Good morning Deni, I see that you have slept well.';
const FIXED_TRANSITION = "Now it's time to direct your attention to what matters most.";

const SIMPLE_CONDITIONS = {
  0: 'clear and sunny', 1: 'mostly clear', 2: 'partly cloudy', 3: 'cloudy',
  45: 'foggy', 48: 'foggy',
  51: 'light rain', 53: 'rain', 55: 'rain',
  56: 'freezing rain', 57: 'freezing rain',
  61: 'light rain', 63: 'rain', 65: 'heavy rain',
  66: 'freezing rain', 67: 'freezing rain',
  71: 'light snow', 73: 'snow', 75: 'heavy snow',
  77: 'snow',
  80: 'rain showers', 81: 'rain showers', 82: 'heavy rain showers',
  85: 'snow showers', 86: 'heavy snow showers',
  95: 'thunderstorms', 96: 'thunderstorms', 99: 'thunderstorms',
};

function checkAuth(req) {
  const cronSecret = process.env.CRON_SECRET;
  const assistantToken = process.env.ASSISTANT_API_TOKEN;
  const header = (req.headers && req.headers.authorization) || '';
  const token = header.indexOf('Bearer ') === 0 ? header.slice(7) : '';
  if (cronSecret && token === cronSecret) return true;
  if (assistantToken && token === assistantToken) return true;
  return false;
}

async function readAppState(supabaseUrl, supabaseKey, key) {
  try {
    const r = await fetch(supabaseUrl + '/rest/v1/app_state?key=eq.' + key + '&select=data', {
      headers: { apikey: supabaseKey, Authorization: 'Bearer ' + supabaseKey },
    });
    if (!r.ok) return null;
    const rows = await r.json();
    return (rows && rows[0] && rows[0].data) || null;
  } catch (e) { return null; }
}

async function upsertAppState(supabaseUrl, supabaseKey, key, data) {
  return fetch(supabaseUrl + '/rest/v1/app_state?on_conflict=key', {
    method: 'POST',
    headers: {
      apikey: supabaseKey,
      Authorization: 'Bearer ' + supabaseKey,
      'Content-Type': 'application/json',
      Prefer: 'resolution=merge-duplicates',
    },
    body: JSON.stringify({ key, data, updated_at: new Date().toISOString() }),
  });
}

// en-CA formats as YYYY-MM-DD directly — used as the cache's
// freshness key so "today" is always evaluated in Evanston's actual
// local calendar day, independent of when/how imprecisely the cron
// itself fired.
export function getTodayDateKey(now) {
  now = now == null ? Date.now() : now;
  return new Intl.DateTimeFormat('en-CA', { timeZone: TIMEZONE, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(now));
}

function formatHourLabel(isoLocal) {
  const hourStr = isoLocal.split('T')[1] || '';
  const hour = parseInt(hourStr.split(':')[0], 10);
  if (!Number.isFinite(hour)) return '';
  const period = hour >= 12 ? 'PM' : 'AM';
  let h12 = hour % 12;
  if (h12 === 0) h12 = 12;
  return h12 + ' ' + period;
}

// Finds the first/last hour today where UV reaches SUNSCREEN_UV_THRESHOLD
// — null if it never does (e.g. an overcast winter day).
export function computeSunscreenWindow(hourlyTimes, hourlyUV, threshold) {
  threshold = threshold == null ? SUNSCREEN_UV_THRESHOLD : threshold;
  let startIdx = -1, endIdx = -1;
  for (let i = 0; i < hourlyUV.length; i++) {
    if (hourlyUV[i] != null && hourlyUV[i] >= threshold) {
      if (startIdx === -1) startIdx = i;
      endIdx = i;
    }
  }
  if (startIdx === -1) return null;
  return { startLabel: formatHourLabel(hourlyTimes[startIdx]), endLabel: formatHourLabel(hourlyTimes[endIdx]) };
}

export function computeUmbrellaAdvice(precipProbMaxPct, threshold) {
  threshold = threshold == null ? UMBRELLA_PRECIP_PROB_THRESHOLD : threshold;
  return precipProbMaxPct != null && precipProbMaxPct >= threshold;
}

// Pure — takes Open-Meteo's parsed JSON response and derives every
// field the weather section needs. Separated from fetchWeather() so
// it's testable with synthetic data, no network call required.
export function deriveWeatherFields(data) {
  const current = (data && data.current) || {};
  const daily = (data && data.daily) || {};
  const hourly = (data && data.hourly) || {};
  const weatherCode = current.weather_code;
  const highF = Array.isArray(daily.temperature_2m_max) ? daily.temperature_2m_max[0] : null;
  const lowF = Array.isArray(daily.temperature_2m_min) ? daily.temperature_2m_min[0] : null;
  const uvIndexMaxToday = Array.isArray(daily.uv_index_max) ? daily.uv_index_max[0] : null;
  const precipProbMaxPct = Array.isArray(daily.precipitation_probability_max) ? daily.precipitation_probability_max[0] : null;
  const hourlyTimes = Array.isArray(hourly.time) ? hourly.time : [];
  const hourlyUV = Array.isArray(hourly.uv_index) ? hourly.uv_index : [];
  return {
    condition: SIMPLE_CONDITIONS[weatherCode] || (weatherCode != null ? 'mixed conditions' : 'unknown conditions'),
    highF, lowF, uvIndexMaxToday, precipProbMaxPct,
    sunscreenWindow: computeSunscreenWindow(hourlyTimes, hourlyUV),
    needUmbrella: computeUmbrellaAdvice(precipProbMaxPct),
  };
}

export async function fetchWeather() {
  const url = 'https://api.open-meteo.com/v1/forecast' +
    '?latitude=' + LAT + '&longitude=' + LON +
    '&timezone=' + encodeURIComponent(TIMEZONE) +
    '&forecast_days=1' +
    '&current=weather_code' +
    '&hourly=uv_index' +
    '&daily=uv_index_max,precipitation_probability_max,temperature_2m_max,temperature_2m_min' +
    '&temperature_unit=fahrenheit&precipitation_unit=inch';
  const r = await fetch(url);
  if (!r.ok) throw new Error('Open-Meteo request failed: ' + r.status);
  const data = await r.json();
  return deriveWeatherFields(data);
}

// Deterministic, no LLM — condition/high-low/UV/sunscreen window/
// umbrella only. Deliberately excludes hydration and any other health
// tip per the explicit spec.
export function buildWeatherSection(w) {
  const parts = [];
  if (w.highF != null && w.lowF != null) {
    parts.push('Today\'s weather is ' + w.condition + ', with a high of ' + Math.round(w.highF) + ' and a low of ' + Math.round(w.lowF) + ' degrees.');
  } else {
    parts.push('Today\'s weather is ' + w.condition + '.');
  }
  if (w.uvIndexMaxToday != null) parts.push('The UV index is ' + w.uvIndexMaxToday + '.');
  if (w.sunscreenWindow) parts.push('Wear sunscreen between ' + w.sunscreenWindow.startLabel + ' and ' + w.sunscreenWindow.endLabel + '.');
  else parts.push('You won\'t need sunscreen today.');
  parts.push(w.needUmbrella ? 'Yes, bring an umbrella today.' : 'No, you won\'t need an umbrella today.');
  return parts.join(' ');
}

// ---------- News (RSS primary, category-matched to Life Context — no web_search tool) ----------

export function parseRSSTitles(xml, limit) {
  const items = [];
  const itemRegex = /<item>([\s\S]*?)<\/item>/g;
  let m;
  while ((m = itemRegex.exec(xml)) && items.length < limit) {
    const titleMatch = /<title>([\s\S]*?)<\/title>/.exec(m[1]);
    if (!titleMatch) continue;
    const title = titleMatch[1].replace(/<!\[CDATA\[/g, '').replace(/\]\]>/g, '').trim();
    if (title) items.push(title);
  }
  return items;
}

async function fetchNewsHeadlines(query) {
  const url = query
    ? 'https://news.google.com/rss/search?q=' + encodeURIComponent(query) + '&hl=en-US&gl=US&ceid=US:en'
    : 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en';
  const r = await fetch(url);
  if (!r.ok) throw new Error('news RSS request failed: ' + r.status);
  const xml = await r.text();
  return parseRSSTitles(xml, 12);
}

// Small fixed set of topics, each backed by its own free/keyless
// Google News RSS search query — this IS the "fixed list of free RSS
// feeds," just parameterized by topic rather than by publisher, since
// Google News RSS is the one feed already proven reliable and
// consistently parseable by parseRSSTitles above. Matching is a plain
// case-insensitive substring check against the Life Context text —
// deliberately simple and predictable over an LLM-driven categorization
// step, which would just be one more thing that could fail.
export const NEWS_CATEGORIES = [
  { id: 'ai_tech', keywords: ['ai', 'artificial intelligence', 'machine learning', 'tech', 'technology', 'software', 'startup', 'computer science', 'programming', 'coding'], query: 'artificial intelligence technology' },
  { id: 'biomedical', keywords: ['biomedical', 'biotech', 'biotechnology', 'medicine', 'medical', 'health research', 'glp-1', 'glp1', 'pharma', 'pharmaceutical', 'clinical', 'life sciences', 'genomics'], query: 'biomedical research health science' },
  { id: 'markets', keywords: ['market', 'markets', 'stock', 'stocks', 'finance', 'financial', 'economy', 'economic', 'investing', 'investment', 'business'], query: 'stock market economy finance' },
];

export function matchNewsCategories(lifeContext) {
  const lower = (lifeContext || '').toLowerCase();
  return NEWS_CATEGORIES.filter((c) => c.keywords.some((k) => lower.includes(k)));
}

// Always fetches the general top-stories feed alongside any matched
// topics (parallel, via allSettled so one dead feed can't take the
// others down with it), dedupes by exact title, caps the combined
// list so the prompt stays a reasonable size.
export async function fetchCategorizedHeadlines(lifeContext) {
  const matched = matchNewsCategories(lifeContext);
  const queries = matched.map((c) => c.query);
  queries.push(null); // general top stories, always included as a baseline
  const settled = await Promise.allSettled(queries.map((q) => fetchNewsHeadlines(q)));
  const seen = new Set();
  const combined = [];
  for (const result of settled) {
    if (result.status !== 'fulfilled') continue;
    for (const title of result.value) {
      if (!seen.has(title)) { seen.add(title); combined.push(title); }
    }
  }
  return combined.slice(0, 20);
}

// No mention of search/RSS/technical details anywhere in this prompt —
// that framing is exactly what caused Claude to write a long apology
// instead of just reporting the news in production. Claude only ever
// sees "here are today's headlines," never "search failed."
export function buildNewsPrompt(lifeContext, headlines) {
  return [
    'Write ONLY the news portion of a spoken-word morning briefing — plain conversational text, no markdown, no headers, no bullet points, no numbered lists, no asterisks.',
    'Report the news directly, the way a person would read it aloud — no preamble, no disclaimers, no meta-commentary, no explanation of how this information was put together.',
    'From the real, current headlines below, pick the 3 most relevant to these interests and summarize each in one or two spoken sentences:',
    lifeContext ? lifeContext : '(not set — pick broadly interesting, non-partisan headlines instead)',
    '',
    'Headlines:',
    headlines.map((h) => '- ' + h).join('\n'),
  ].join('\n');
}

async function newsViaRSSAndLLM(client, lifeContext, headlines) {
  if (!headlines.length) throw new Error('no headlines available from any RSS feed');
  const response = await client.messages.create({
    model: 'claude-opus-4-8',
    max_tokens: 1024,
    messages: [{ role: 'user', content: buildNewsPrompt(lifeContext, headlines) }],
  });
  return response.content.filter((b) => b.type === 'text').map((b) => b.text).join(' ').trim();
}

export function newsViaRawHeadlines(headlines) {
  return 'In the news: ' + headlines.slice(0, 3).join('. ') + '.';
}

// Three-tier fallback, all rooted in the same code-fetched headlines:
// Claude summarizes them -> if the LLM call fails, use the raw
// headlines directly, no LLM -> if RSS itself is unreachable, one
// short, honest sentence. Never throws, never returns an empty
// string, and the final fallback is deliberately ONE short sentence,
// not a paragraph.
export async function composeNewsSection(client, lifeContext) {
  let headlines = [];
  try {
    headlines = await fetchCategorizedHeadlines(lifeContext);
  } catch (e) {
    headlines = [];
  }
  try {
    const text = await newsViaRSSAndLLM(client, lifeContext, headlines);
    if (text) return { text, source: 'rss_llm' };
    throw new Error('LLM returned no text');
  } catch (e1) {
    if (headlines.length) {
      return { text: newsViaRawHeadlines(headlines), source: 'rss_raw' };
    }
    return { text: 'I couldn\'t pull today\'s news.', source: 'unavailable' };
  }
}

// ---------- Cache ----------

async function readCachedBriefing(supabaseUrl, supabaseKey) {
  const state = await readAppState(supabaseUrl, supabaseKey, 'briefing_cache');
  const cached = state && state.briefing_v1;
  if (!cached || typeof cached.reply !== 'string' || !cached.reply) return null;
  if (cached.dateKey !== getTodayDateKey()) return null;
  return cached;
}

export async function generateBriefing(apiKey, supabaseUrl, supabaseKey) {
  const weather = await fetchWeather();
  const weatherSection = buildWeatherSection(weather);

  const lifeContextState = await readAppState(supabaseUrl, supabaseKey, 'life_context');
  const lifeContext = (lifeContextState && typeof lifeContextState.life_context_v1 === 'string') ? lifeContextState.life_context_v1 : '';

  const client = new Anthropic({ apiKey });
  const { text: newsSection, source: newsSource } = await composeNewsSection(client, lifeContext);

  const reply = [FIXED_OPENING, weatherSection, FIXED_TRANSITION, newsSection].join(' ').replace(/\s+/g, ' ').trim();
  const generatedAt = Date.now();
  const dateKey = getTodayDateKey(generatedAt);

  await upsertAppState(supabaseUrl, supabaseKey, 'briefing_cache', { briefing_v1: { reply, newsSource, generatedAt, dateKey } });

  return { reply, newsSource, generatedAt };
}

export default async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).json({ ok: false, error: 'method not allowed' });
  if (!checkAuth(req)) return res.status(401).json({ ok: false, error: 'invalid or missing bearer token' });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return res.status(500).json({ ok: false, error: 'ANTHROPIC_API_KEY not configured' });
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY;
  if (!supabaseUrl || !supabaseKey) return res.status(500).json({ ok: false, error: 'server not configured (missing SUPABASE_URL / SUPABASE_ANON_KEY)' });

  const cached = await readCachedBriefing(supabaseUrl, supabaseKey);
  if (cached) {
    return res.status(200).json({ ok: true, reply: cached.reply, newsSource: cached.newsSource, generatedAt: cached.generatedAt, cached: true });
  }

  try {
    const { reply, newsSource, generatedAt } = await generateBriefing(apiKey, supabaseUrl, supabaseKey);
    return res.status(200).json({ ok: true, reply, newsSource, generatedAt, cached: false });
  } catch (e) {
    return res.status(200).json({ ok: false, error: 'briefing generation failed: ' + (e && e.message ? e.message : String(e)) });
  }
}
